name: Build, Test (API), and Push images

env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lowercase owner/repo for GHCR paths
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo "REPO_LC=${REPO_NAME,,}" >> $GITHUB_ENV
          echo "IMAGE_NS=${{ env.REGISTRY }}/${OWNER_LC}/${REPO_LC}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------- Build images (no push yet) ----------
      - name: Build events-service
        uses: docker/build-push-action@v6
        with:
          context: ./src/microservices/events
          file: ./src/microservices/events/Dockerfile
          platforms: linux/amd64
          push: false
          tags: |
            ${{ env.IMAGE_NS }}/events-service:sha-${{ github.sha }}
            ${{ env.IMAGE_NS }}/events-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build proxy-service
        uses: docker/build-push-action@v6
        with:
          context: ./src/microservices/proxy
          file: ./src/microservices/proxy/Dockerfile
          platforms: linux/amd64
          push: false
          tags: |
            ${{ env.IMAGE_NS }}/proxy-service:sha-${{ github.sha }}
            ${{ env.IMAGE_NS }}/proxy-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---------- Spin up the stack & wait ----------
      - name: Compose up infra & services
        run: |
          docker compose up -d --build \
            zookeeper kafka kafka-ui postgres \
            monolith movies-service events-service proxy-service

      - name: Wait for readiness
        run: |
          set -e
          # ждём по очереди основные health endpoints
          for i in {1..90}; do
            ok=1
            curl -fsS http://localhost:8080/health    || ok=0
            curl -fsS http://localhost:8081/health    || ok=0
            curl -fsS http://localhost:8082/healthz   || ok=0
            curl -fsS http://localhost:8000/health    || ok=0
            if [ $ok -eq 1 ]; then echo "All services are healthy"; break; fi
            sleep 2
          done
          [ $ok -eq 1 ]

      # ---------- Install & run API tests ----------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: tests/postman/package-lock.json

      - name: Install test deps
        working-directory: tests/postman
        run: npm ci

      - name: Run API tests (local)
        working-directory: tests/postman
        run: npm run test:local

      - name: Dump logs on failure
        if: failure()
        run: |
          docker compose ps
          docker compose logs --no-color zookeeper kafka postgres | tail -n 200
          docker compose logs --no-color monolith movies-service events-service proxy-service | tail -n 400

      # ---------- Push images if tests passed ----------
      - name: Push events-service
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: ./src/microservices/events
          file: ./src/microservices/events/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NS }}/events-service:sha-${{ github.sha }}
            ${{ env.IMAGE_NS }}/events-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push proxy-service
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: ./src/microservices/proxy
          file: ./src/microservices/proxy/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NS }}/proxy-service:sha-${{ github.sha }}
            ${{ env.IMAGE_NS }}/proxy-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
